defaults:
- data: diffusiondownscaling
- dataloader: hindcast_o320
- diagnostics: evaluation
- system: diffusiondownscaling
- graph: existing
- model: graphtransformer_diffusiondownscaling
- training: diffusiondownscaling
- _self_


# set to true to switch on config validation
config_validation: True
