defaults:
- data: multi
- dataloader: multi
- diagnostics: evaluation_multi
- system: example
- graph: multi_scale
- truncation: none
- model: graphtransformer
- training: multi
- _self_

config_validation: True

system:
  input:
    graph: graph_anemoi_new_${data.resolution}.pt

    # Primary dataset for ERA5
    dataset: aifs-ea-an-oper-0001-mars-${data.resolution}-1979-2023-6h-v8

    # Secondary dataset for CERRA (using same file for debugging)
    dataset_b: aifs-ea-an-oper-0001-mars-${data.resolution}-1979-2023-6h-v8

  output:
    root: ${oc.env:SCRATCH}/anemoi-test/${data.resolution}/

  hardware:
    accelerator: auto
    num_gpus_per_node: 1
    num_nodes: 1
    num_gpus_per_model: 1

diagnostics:
  log:
    mlflow:
      enabled: False
      tracking_uri: None
    wandb:
      enabled: False
      entity: example
