# Configuration to disable all plot callbacks
callbacks: []

asynchronous: False
datashader: False
frequency:
  batch: 999999999  # Effectively never
  epoch: 999999999  # Effectively never

parameters: []
sample_idx: 0
precip_and_related_fields: []

colormaps: {}

datasets_to_plot: []
