---
# Reusable self-smoothing projection parameters (KNN=128, sigma~240km).

node_name: smooth
reference_node_name: ${graph.data}
edge_weight_attribute: gauss_weight
gaussian_norm: l1
num_nearest_neighbours: 128
sigma: 0.03768
