---
# Self-smoothing projection parameters for o96 (~100 km), KNN=64.

node_name: smooth
reference_node_name: ${graph.data}
edge_weight_attribute: gauss_weight
gaussian_norm: l1
num_nearest_neighbours: 64
sigma: 0.06280
