---
# Reusable self-smoothing projection parameters (KNN=16, sigma~30km).

node_name: smooth
reference_node_name: ${graph.data}
edge_weight_attribute: gauss_weight
gaussian_norm: l1
num_nearest_neighbours: 16
sigma: 0.00471
