---
# Self-smoothing projection parameters for n320 (~30 km), KNN=128.

node_name: smooth
reference_node_name: ${graph.data}
edge_weight_attribute: gauss_weight
gaussian_norm: l1
num_nearest_neighbours: 128
sigma: 0.03768
