datasets:
  in_lres: {}  # No scalers needed for input dataset
  in_hres: {}  # No scalers needed for input dataset
  out_hres:
    # Several scalers can be added here. In order to be applied their names must be included in the loss.
    # scaler name must be included in `scalers` in the losses for this to be applied.
    general_variable:
      _target_: anemoi.training.losses.scalers.GeneralVariableLossScaler
      weights:
        default: 1
        q: 2
        t: 1
        u: 1.5
        v: 1.5
        w: 2
        z: 0.5
        sp: 1.5
        10u: 2.5
        10v: 2.5
        2d: 2
        tp: 2
        cp: 2
        msl: 2
        2t: 2
        tcw: 1
        skt: 0.5

    pressure_level:
      _target_: anemoi.training.losses.scalers.LinearVariableLevelScaler
      group: pl
      y_intercept: 0.0
      slope: 0.0001659751037

    # mask NaNs with zeros in the loss function
    nan_mask_weights:
      _target_: anemoi.training.losses.scalers.NaNMaskScaler

    # tendency scalers
    # scale the prognostic losses by the stdev of the variable tendencies (e.g. the 6-hourly differences of the data)
    # useful if including slow vs fast evolving variables in the training (e.g. Land/Ocean vs Atmosphere)
    # if using this option 'variable_loss_scalings' should all be set close to 1.0 for prognostic variables
    stdev_tendency:
      _target_: anemoi.training.losses.scalers.StdevTendencyScaler

    var_tendency:
      _target_: anemoi.training.losses.scalers.VarTendencyScaler

    # Scalers from node attributes
    node_weights:
      _target_: anemoi.training.losses.scalers.GraphNodeAttributeScaler
      nodes_name: ${graph.data}
      nodes_attribute_name: area_weight
      norm: unit-sum
