matrices:
  path: null
  down: null
  up: null

residual:
  _target_: anemoi.models.layers.residual.TruncatedConnection
  truncation_down_file_path: ${truncation.matrices.down}
  truncation_up_file_path: ${truncation.matrices.up}
  truncation_matrices_path: ${truncation.matrices.path}
